### ISSUE TITLE
pathinfo function will not check current image contents.

### ISSUE THREAD

**Issue by peter279k** [selective-php/image#1]
As title, the `pathinfo` function will not check the image contents and this will be incorrect for detecting image formats.

# Instruction

- For example, we have a `road.png`  file name with the `jpg` contents.
- Using the `pathinfo` to detect image extension.
![image](https://user-images.githubusercontent.com/9021747/56867672-8b48aa80-6a1a-11e9-876b-3f82cab46b6e.png)
- Actually, it's the `jpg` contents when using the `file` command.
![image](https://user-images.githubusercontent.com/9021747/56867683-af0bf080-6a1a-11e9-811f-19e8922a7e7a.png)
- To resolve this issue, we can consider replacing `pathinfo` with [exif_imagetype](https://php.net/manual/en/function.exif-imagetype.php) function.

![image](https://user-images.githubusercontent.com/9021747/56867702-f4302280-6a1a-11e9-8f55-b022b42abb46.png)

**Comment by odan** [comment]
That's good. But we should check if the `exif_imagetype` exists and maybe use `pathinfo` as "fallback" function if exif is not installed. Then the `exif` extension would be still optional, but recommended.

**Comment by peter279k** [comment]
@odan, thank you for your reply.

I think we can let the `exif` extension in `suggest` block and using the `pathinfo` function if the `exif` extension is not loaded.
