### ISSUE TITLE
Webp image format support

### ISSUE THREAD

**Issue by peter279k** [selective-php/image#3]
As title, it looks like the `webp` image format doesn't support on this image package.

If possible, we can support this image format. But this work is too hard/complicated.

Here are some problems that we need to concern:

- The `webp` image check is available sine `php-7.1` in `exif_imagetype` function.
**This should be fine because the package require minimum PHP version is `7.1`.**
- In Travis CI build, it seems that the `imagewebp` will be undefined, even the `GD` extension is loaded.
This issue I suffered yesterday. And I also reported related [discussion](https://travis-ci.community/t/how-to-enable-webp-image-format-support-in-php-7/3209) on Travis CI community.

**The hard-core way is about using the `sudo` to install a PHP version without PHP version  provided by `phpenv`.**

**Comment by odan** [comment]
There are too many technical issues and I never saw this file-format in real live. I think we should not add support for the exotic / rare file format.

**Comment by peter279k** [comment]
@odan, thank you for your reply.

I close this issue until we start considering this again :).
