### ISSUE TITLE
string function call mapping

### ISSUE THREAD

**Issue by peter279k** [selective-php/image#4]
As title, look at this [code](https://github.com/selective-php/image/blob/master/src/Image/Image.php#L36).

It seems that we use `switch...case` to dispatch the current image function.

However, we can also use the string function call to reduce this condition.

Consider following code snippets:

```php
$image = 'image';
$extension = 'jpeg';

($image . $extension)(......);
```

But I don't make sure that this performance would be good.

**Comment by odan** [comment]
This would make problems with the static code analyse (phpstan) I will add in the next days. It will also make debugging and passing parameters harder.
