### ISSUE TITLE
Modify PHP version requirements

### ISSUE THREAD

**Issue by peter279k** [selective-php/image#6]
As title, it looks like we have to modify minimum PHP version requirement.

It presents the minimum PHP version is `7.2` in `README`, but it defines minimum PHP version is `7.1` at least in [composer.json](https://github.com/selective-php/image/blob/master/composer.json#L13).

**Comment by odan** [comment]
The minimum version has changes due to support for the BMP format. Can you create a PR to update composer.json?

**Comment by peter279k** [comment]
Hi @odan, sure. I will create PR.
